-- Table: personal.variable_relationships

CREATE TABLE personal.variable_relationships (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES core.profiles(id),
    cause_variable_id INTEGER NOT NULL REFERENCES reference.variables(id),
    effect_variable_id INTEGER NOT NULL REFERENCES reference.variables(id),
    correlation_coefficient DOUBLE PRECISION,
    correlation_significance DOUBLE PRECISION,
    confidence_interval_lower DOUBLE PRECISION,
    confidence_interval_upper DOUBLE PRECISION,
    onset_delay INTEGER,
    duration_of_action INTEGER,
    number_of_pairs INTEGER,
    value_predicting_high_outcome DOUBLE PRECISION,
    value_predicting_low_outcome DOUBLE PRECISION,
    optimal_pearson_product INTEGER,
    vote INTEGER,
    statistical_significance DOUBLE PRECISION,
    cause_changes INTEGER,
    effect_changes INTEGER,
    qm_score DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMPTZ,
    status VARCHAR(25),
    cause_variable_category_id INTEGER,
    effect_variable_category_id INTEGER,
    forward_pearson_correlation_coefficient DOUBLE PRECISION,
    onset_delay_with_strongest_pearson_correlation INTEGER,
    number_of_days_following_onset_delay INTEGER,
    reverse_pearson_correlation_coefficient DOUBLE PRECISION,
    predictive_pearson_correlation_coefficient DOUBLE PRECISION,
    predicts_high_effect_change INTEGER,
    predicts_low_effect_change INTEGER,
    p_value DOUBLE PRECISION,
    t_value DOUBLE PRECISION,
    critical_t_value DOUBLE PRECISION,
    confidence_level DOUBLE PRECISION,
    relationship_strength INTEGER,
    relationship_type VARCHAR(25),
    study_status VARCHAR(25),
    charts JSONB,
    predictor_data_sources TEXT,
    outcome_data_sources TEXT,
    number_of_predictor_users INTEGER,
    number_of_outcome_users INTEGER,
    number_of_predictor_measurements INTEGER,
    number_of_outcome_measurements INTEGER,
    predictor_filling_value INTEGER,
    outcome_filling_value INTEGER,
    predictor_maximum_allowed_value DOUBLE PRECISION,
    outcome_maximum_allowed_value DOUBLE PRECISION,
    predictor_minimum_allowed_value DOUBLE PRECISION,
    outcome_minimum_allowed_value DOUBLE PRECISION,
    predictor_unit_id INTEGER,
    outcome_unit_id INTEGER,
    interesting INTEGER,
    newest_data_at TIMESTAMPTZ,
    oldest_data_at TIMESTAMPTZ,
    cause_variable_category_name VARCHAR(125),
    effect_variable_category_name VARCHAR(125),
    predictor_data_source_name VARCHAR(125),
    outcome_data_source_name VARCHAR(125),
    predictor_earliest_measurement_start_at TIMESTAMPTZ,
    predictor_latest_measurement_start_at TIMESTAMPTZ,
    outcome_earliest_measurement_start_at TIMESTAMPTZ,
    outcome_latest_measurement_start_at TIMESTAMPTZ,
    predictor_error INTEGER,
    outcome_error INTEGER,
    most_common_connector_id INTEGER,
    wp_post_id BIGINT,
    cause_variable_unit_abbreviated_name VARCHAR(125),
    effect_variable_unit_abbreviated_name VARCHAR(125),
    cause_variable_unit_name VARCHAR(125),
    effect_variable_unit_name VARCHAR(125),
    predictor_data_lab_test_type_id INTEGER,
    outcome_data_lab_test_type_id INTEGER,
    predictor_data_lab_test_type_name VARCHAR(125),
    outcome_data_lab_test_type_name VARCHAR(125),
    predictor_data_lab_test_type_category_name VARCHAR(125),
    outcome_data_lab_test_type_category_name VARCHAR(125),
    predictor_data_lab_test_type_category_id INTEGER,
    outcome_data_lab_test_type_category_id INTEGER,
    predictor_data_lab_test_type_abbreviated_name VARCHAR(125),
    outcome_data_lab_test_type_abbreviated_name VARCHAR(125),
    predictor_data_lab_test_type_unit_name VARCHAR(125),
    outcome_data_lab_test_type_unit_name VARCHAR(125),
    predictor_data_lab_test_type_unit_abbreviated_name VARCHAR(125),
    outcome_data_lab_test_type_unit_abbreviated_name VARCHAR(125),
    predictor_data_lab_test_type_unit_id INTEGER,
    outcome_data_lab_test_type_unit_id INTEGER,
    predictor_data_lab_test_type_category_combination_operation VARCHAR(125),
    outcome_data_lab_test_type_category_combination_operation VARCHAR(125),
    predictor_data_lab_test_type_category_filling_value INTEGER,
    outcome_data_lab_test_type_category_filling_value INTEGER,
    predictor_data_lab_test_type_category_maximum_value DOUBLE PRECISION,
    outcome_data_lab_test_type_category_maximum_value DOUBLE PRECISION,
    predictor_data_lab_test_type_category_minimum_value DOUBLE PRECISION,
    outcome_data_lab_test_type_category_minimum_value DOUBLE PRECISION,
    predictor_data_lab_test_type_category_onset_delay INTEGER,
    outcome_data_lab_test_type_category_onset_delay INTEGER,
    predictor_data_lab_test_type_category_duration_of_action INTEGER,
    outcome_data_lab_test_type_category_duration_of_action INTEGER,
    predictor_data_lab_test_type_category_filling_type VARCHAR(125),
    outcome_data_lab_test_type_category_filling_type VARCHAR(125)
);

-- Add column comments
COMMENT ON COLUMN personal.variable_relationships.qm_score IS 'Quality of data and relationship (0-100)';
