-- AI Generated Relationships Seed File --
-- Generated on: 2025-04-27T05:43:38.969Z --
-- Predictor Category: intake-and-interventions --
-- AI Model: models/gemini-1.5-pro-latest --

-- Insert data into public.citations
INSERT INTO public."citations" ("id", "type", "title", "journal_or_publisher", "publication_year", "retrieved_at")
VALUES
  ('cite-models-gemini-1-5-pro-latest', 'other', 'AI Generated Relationships (models/gemini-1.5-pro-latest)', 'Google AI', 2025, '2025-04-27T05:43:38.969Z')
ON CONFLICT (id) DO NOTHING;

-- Insert data into public.global_variables
INSERT INTO public."global_variables" ("default_unit_id", "description", "id", "name", "variable_category_id")
VALUES
  ('milligrams-per-deciliter', 'Measures blood glucose levels after a period of fasting, typically 8-12 hours.', 'fasting-blood-glucose', 'Fasting Blood Glucose', 'health-and-physiology'),
  ('percent', 'Measures average blood glucose levels over the past 2-3 months.', 'hba1c', 'HbA1c', 'health-and-physiology'),
  ('kilogram', 'Measures overall body mass.', 'body-weight', 'Body Weight', 'health-and-physiology'),
  ('centimeter', 'Measures the circumference of the waist, an indicator of abdominal fat.', 'waist-circumference', 'Waist Circumference', 'health-and-physiology'),
  ('millimoles-per-liter', 'Measures blood insulin levels after a period of fasting.', 'fasting-insulin', 'Fasting Insulin', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'Measures blood triglyceride levels, a type of fat found in the blood.', 'triglycerides', 'Triglycerides', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'Measures blood levels of high-density lipoprotein cholesterol, often referred to as "good" cholesterol.', 'hdl-cholesterol', 'HDL Cholesterol', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'Measures blood levels of low-density lipoprotein cholesterol, often referred to as "bad" cholesterol.', 'ldl-cholesterol', 'LDL Cholesterol', 'health-and-physiology'),
  ('dimensionless-unit', 'A calculated measure of insulin resistance based on fasting glucose and insulin levels.', 'insulin-resistance-homa-ir', 'Insulin Resistance (HOMA-IR)', 'health-and-physiology'),
  ('per-day', 'Records the daily dosage of Metformin taken.', 'metformin-dosage', 'Metformin Dosage', 'intake-and-interventions'),
  ('one-to-ten-scale', 'Measures the severity of gastrointestinal side effects, such as nausea, diarrhea, and abdominal discomfort, often experienced with Metformin.', 'gastrointestinal-side-effects', 'Gastrointestinal Side Effects', 'health-and-physiology'),
  ('millimeters-of-mercury', 'The pressure in the arteries when the heart beats.', 'systolic-blood-pressure', 'Systolic Blood Pressure', 'health-and-physiology'),
  ('millimeters-of-mercury', 'The pressure in the arteries when the heart rests between beats.', 'diastolic-blood-pressure', 'Diastolic Blood Pressure', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'A measure of kidney function.', 'blood-creatinine', 'Blood Creatinine', 'health-and-physiology'),
  ('millimoles-per-liter', 'A measure of potassium levels in the blood.', 'blood-potassium', 'Blood Potassium', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'A measure of kidney function.', 'blood-urea-nitrogen-bun', 'Blood Urea Nitrogen (BUN)', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'A measure of uric acid levels in the blood, relevant for gout.', 'uric-acid', 'Uric Acid', 'health-and-physiology'),
  ('dimensionless-unit', 'Presence and severity of swelling, often in the legs and feet.', 'edema-swelling', 'Edema (Swelling)', 'health-and-physiology'),
  ('dimensionless-unit', 'Presence and frequency of cough.', 'cough', 'Cough', 'health-and-physiology'),
  ('dimensionless-unit', 'Experiences of dizziness or lightheadedness.', 'dizziness', 'Dizziness', 'health-and-physiology'),
  ('milliliter', 'The amount of urine produced over a period of time.', 'urine-output', 'Urine Output', 'health-and-physiology'),
  ('millimeter', 'Number of swollen joints, a measure of disease activity in rheumatoid arthritis and other inflammatory conditions.', 'swollen-joint-count', 'Swollen Joint Count', 'health-and-physiology'),
  ('millimeter', 'Number of tender joints, a measure of disease activity in rheumatoid arthritis and other inflammatory conditions.', 'tender-joint-count', 'Tender Joint Count', 'health-and-physiology'),
  ('dimensionless-unit', 'A blood marker for inflammation.', 'crp-c-reactive-protein', 'CRP (C-Reactive Protein)', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'A blood marker for inflammation.', 'esr-erythrocyte-sedimentation-rate', 'ESR (Erythrocyte Sedimentation Rate)', 'health-and-physiology'),
  ('dimensionless-unit', 'A composite score assessing disease activity in rheumatoid arthritis.', 'das28-disease-activity-score-28', 'DAS28 (Disease Activity Score 28)', 'health-and-physiology'),
  ('zero-to-ten-scale', 'Patient-reported pain level.', 'pain-score', 'Pain Score', 'health-and-physiology'),
  ('zero-to-ten-scale', 'Patient-reported fatigue level.', 'fatigue-score', 'Fatigue Score', 'health-and-physiology'),
  ('dimensionless-unit', 'A measure of functional disability in rheumatoid arthritis.', 'haq-di-health-assessment-questionnaire-disability-index', 'HAQ-DI (Health Assessment Questionnaire Disability Index)', 'health-and-physiology'),
  ('dimensionless-unit', 'A measure of health-related quality of life.', 'sf-36-short-form-36-health-survey', 'SF-36 (Short Form 36 Health Survey)', 'health-and-physiology'),
  ('per-month', 'Number of disease flares experienced per month.', 'flare-frequency', 'Flare Frequency', 'health-and-physiology'),
  ('one-to-ten-scale', 'Measure of depressive symptoms, such as sadness, loss of interest, and fatigue, often using standardized scales like PHQ-9 or HAM-D.', 'depression-severity', 'Depression Severity', 'mental-and-emotional-state'),
  ('one-to-ten-scale', 'Assessment of anxiety symptoms, including worry, nervousness, and fear, often using scales like GAD-7 or HAM-A.', 'anxiety-severity', 'Anxiety Severity', 'mental-and-emotional-state'),
  ('dimensionless-unit', 'Subjective assessment of sleep quality, including duration, efficiency, and perceived restfulness, often using scales like PSQI.', 'sleep-quality', 'Sleep Quality', 'health-and-physiology'),
  ('dimensionless-unit', 'Overall sense of well-being and life satisfaction, often measured using questionnaires like EQ-5D or SF-36.', 'quality-of-life', 'Quality of Life', 'mental-and-emotional-state'),
  ('dimensionless-unit', 'Occurrence and severity of adverse effects associated with escitalopram, such as nausea, insomnia, or sexual dysfunction.', 'side-effects', 'Side Effects', 'health-and-physiology'),
  ('dimensionless-unit', 'Presence and intensity of thoughts about suicide, assessed through clinical interviews or self-report measures.', 'suicidal-ideation', 'Suicidal Ideation', 'mental-and-emotional-state'),
  ('dimensionless-unit', 'Extent to which the patient follows the prescribed escitalopram regimen, measured by self-report, pill counts, or prescription refills.', 'treatment-adherence', 'Treatment Adherence', 'intake-and-interventions'),
  ('milligram', 'Daily dose of escitalopram prescribed and taken by the patient.', 'escitalopram-dosage', 'Escitalopram Dosage', 'intake-and-interventions'),
  ('millimeter', 'Measures the maximum speed of expiration, often used to assess airway obstruction.', 'peak-expiratory-flow-pef', 'Peak Expiratory Flow (PEF)', 'health-and-physiology'),
  ('dimensionless-unit', 'Number of breaths per minute.', 'respiratory-rate', 'Respiratory Rate', 'health-and-physiology'),
  ('millimeters-of-mercury', 'A measure of oxygen in arterial blood.', 'partial-pressure-of-oxygen-pao2', 'Partial Pressure of Oxygen (PaO2)', 'health-and-physiology'),
  ('percent', 'Percentage of hemoglobin saturated with oxygen.', 'oxygen-saturation-spo2', 'Oxygen Saturation (SpO2)', 'health-and-physiology'),
  ('millimeter', 'Volume of air exhaled during the first second of forced expiration.', 'forced-expiratory-volume-in-1-second-fev1', 'Forced Expiratory Volume in 1 second (FEV1)', 'health-and-physiology'),
  ('dimensionless-unit', 'Number of wheezing episodes experienced over a period of time.', 'wheezing-episodes', 'Wheezing Episodes', 'health-and-physiology'),
  ('one-to-ten-scale', 'Subjective rating of shortness of breath.', 'dyspnea-score', 'Dyspnea Score', 'health-and-physiology'),
  ('hour', 'Frequency of albuterol inhaler use for symptom relief.', 'rescue-inhaler-use', 'Rescue Inhaler Use', 'intake-and-interventions'),
  ('milligram', 'Total amount of albuterol administered over a period of time.', 'albuterol-dosage', 'Albuterol Dosage', 'intake-and-interventions'),
  ('day', 'Number of days spent in the hospital due to respiratory issues.', 'hospitalization-days', 'Hospitalization Days', 'health-and-physiology'),
  ('dimensionless-unit', 'Number of emergency room visits due to respiratory issues.', 'emergency-room-visits', 'Emergency Room Visits', 'health-and-physiology'),
  ('percent', 'Percentage of total body mass that is composed of fat.', 'body-fat-percentage', 'Body Fat Percentage', 'health-and-physiology'),
  ('kilocalorie', 'Total energy consumed through food and beverages.', 'caloric-intake', 'Caloric Intake', 'intake-and-interventions'),
  ('dimensionless-unit', 'Subjective rating of hunger or desire to eat, often measured on a scale.', 'appetite-level', 'Appetite Level', 'mental-and-emotional-state'),
  ('dimensionless-unit', 'Severity of anxiety symptoms, potentially measured using scales like the Hamilton Anxiety Rating Scale (HAM-A).', 'anxiety-symptoms', 'Anxiety Symptoms', 'mental-and-emotional-state'),
  ('dimensionless-unit', 'Self-reported pain intensity, often measured on a numerical rating scale (e.g., 0-10).', 'pain-level', 'Pain Level', 'health-and-physiology'),
  ('day', 'Duration of time until recurrence of symptoms or condition.', 'time-to-relapse', 'Time to Relapse', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'The concentration of ketamine in the blood plasma.', 'ketamine-plasma-concentration', 'Ketamine Plasma Concentration', 'health-and-physiology'),
  ('dimensionless-unit', 'Assessment of perceptual distortions, detachment from reality, and other dissociative experiences.', 'dissociative-symptoms', 'Dissociative Symptoms', 'mental-and-emotional-state'),
  ('hour', 'The length of time the therapeutic effects of ketamine last.', 'duration-of-effect', 'Duration of Effect', 'health-and-physiology'),
  ('milligram', 'A marker of inflammation.', 'c-reactive-protein-crp', 'C-Reactive Protein (CRP)', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'A marker of iron stores and inflammation.', 'ferritin', 'Ferritin', 'health-and-physiology'),
  ('dimensionless-unit', 'All-cause mortality.', 'mortality', 'Mortality', 'health-and-physiology'),
  ('day', 'Number of days spent in the hospital.', 'hospital-length-of-stay', 'Hospital Length of Stay', 'health-and-physiology'),
  ('dimensionless-unit', 'Whether mechanical ventilation was required (yes/no or number of days).', 'need-for-mechanical-ventilation', 'Need for Mechanical Ventilation', 'health-and-physiology'),
  ('celsius', 'Patient''s body temperature.', 'body-temperature', 'Body Temperature', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'A marker of blood clotting.', 'd-dimer', 'D-dimer', 'health-and-physiology'),
  ('milliliter', 'A pro-inflammatory cytokine.', 'interleukin-6-il-6', 'Interleukin-6 (IL-6)', 'health-and-physiology'),
  ('milligram', 'Daily dosage of aspirin consumed.', 'aspirin-dosage', 'Aspirin Dosage', 'intake-and-interventions'),
  ('percent', 'The clumping together of platelets, which can lead to blood clots.', 'platelet-aggregation', 'Platelet Aggregation', 'health-and-physiology'),
  ('dimensionless-unit', 'Instances of bleeding, including nosebleeds, gastrointestinal bleeding, etc.', 'bleeding-events', 'Bleeding Events', 'health-and-physiology'),
  ('dimensionless-unit', 'Occurrence of a heart attack.', 'myocardial-infarction-heart-attack', 'Myocardial Infarction (Heart Attack)', 'health-and-physiology'),
  ('dimensionless-unit', 'Occurrence of a stroke.', 'stroke', 'Stroke', 'health-and-physiology'),
  ('one-to-ten-scale', 'Severity of headache pain.', 'headache-pain', 'Headache Pain', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'Concentration of salicylate (the active ingredient in aspirin) in the blood.', 'salicylate-level', 'Salicylate Level', 'health-and-physiology'),
  ('millimeters-of-mercury', 'Measurement of blood pressure, including systolic and diastolic pressures.', 'blood-pressure', 'Blood Pressure', 'health-and-physiology'),
  ('millimeter', 'Measurement of swelling or inflammation, typically by measuring the diameter of the affected area.', 'swelling-diameter', 'Swelling (Diameter)', 'health-and-physiology'),
  ('hour', 'The length of time pain is experienced.', 'pain-duration', 'Pain Duration', 'health-and-physiology'),
  ('dimensionless-unit', 'Self-reported severity of headache pain, often measured on a scale.', 'headache-severity', 'Headache Severity', 'health-and-physiology'),
  ('milligram', 'The amount of Ibuprofen taken.', 'ibuprofen-dosage', 'Ibuprofen Dosage', 'intake-and-interventions'),
  ('day', 'How often Ibuprofen is taken over a period of time.', 'frequency-of-ibuprofen-use', 'Frequency of Ibuprofen Use', 'intake-and-interventions'),
  ('milligrams-per-deciliter', 'Blood glucose level measured after an overnight fast.', 'fasting-plasma-glucose', 'Fasting Plasma Glucose', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'Blood glucose level measured after a meal.', 'postprandial-glucose', 'Postprandial Glucose', 'health-and-physiology'),
  ('per-day', 'Number of instances of low blood sugar.', 'hypoglycemia-episodes', 'Hypoglycemia Episodes', 'health-and-physiology'),
  ('dimensionless-unit', 'Measure of how well the patient follows the prescribed medication regimen.', 'medication-adherence', 'Medication Adherence', 'intake-and-interventions'),
  ('per-day', 'Number of panic attacks experienced per day or week.', 'frequency-of-panic-attacks', 'Frequency of Panic Attacks', 'mental-and-emotional-state'),
  ('milligram', 'Daily dosage of Venlafaxine administered.', 'venlafaxine-dosage', 'Venlafaxine Dosage', 'intake-and-interventions'),
  ('one-to-ten-scale', 'Severity of side effects experienced, rated on a scale.', 'side-effects-severity', 'Side Effects Severity', 'health-and-physiology'),
  ('kilogram', 'Body weight measurement.', 'weight', 'Weight', 'health-and-physiology'),
  ('per-minute', 'Resting heart rate measurement.', 'heart-rate', 'Heart Rate', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'The overall amount of cholesterol in the blood.', 'total-cholesterol', 'Total Cholesterol', 'health-and-physiology'),
  ('dimensionless-unit', 'Instances of heart attack, stroke, or other cardiovascular issues.', 'cardiovascular-events', 'Cardiovascular Events', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'An enzyme found in the heart, brain, and skeletal muscles. Elevated levels may indicate muscle damage.', 'creatine-kinase-ck', 'Creatine Kinase (CK)', 'health-and-physiology'),
  ('dimensionless-unit', 'A panel of blood tests used to assess liver health, including ALT, AST, and ALP.', 'liver-function-tests', 'Liver Function Tests', 'health-and-physiology'),
  ('dimensionless-unit', 'Reports of muscle pain, weakness, or tenderness, potentially related to statin use.', 'muscle-symptoms', 'Muscle Symptoms', 'health-and-physiology'),
  ('year-age', 'Measures the length of life from birth to death.', 'lifespan', 'Lifespan', 'health-and-physiology'),
  ('year-age', 'Measures the length of time an individual lives in good health, free from serious disease or disability.', 'healthspan', 'Healthspan', 'health-and-physiology'),
  ('dimensionless-unit', 'A measure of overall health and vulnerability to adverse health outcomes, calculated as the proportion of health deficits present in an individual.', 'frailty-index', 'Frailty Index', 'health-and-physiology'),
  ('milligrams-per-deciliter', 'A blood test used to assess kidney function.', 'creatinine', 'Creatinine', 'health-and-physiology'),
  ('milliliter', 'A measure of kidney function, calculated from creatinine levels, age, and other factors.', 'estimated-glomerular-filtration-rate-egfr', 'Estimated Glomerular Filtration Rate (eGFR)', 'health-and-physiology'),
  ('one-to-ten-scale', 'A composite score assessing various aspects of cognitive function, such as memory, attention, and executive function.', 'cognitive-function-score', 'Cognitive Function Score', 'cognitive-performance'),
  ('second', 'Measures the time it takes to respond to a stimulus.', 'reaction-time', 'Reaction Time', 'cognitive-performance'),
  ('dimensionless-unit', 'Measures the force exerted by hand muscles, often used as an indicator of overall muscle strength and physical function.', 'grip-strength', 'Grip Strength', 'health-and-physiology'),
  ('meter', 'Measures walking speed over a short distance, used as an indicator of mobility and physical function.', 'gait-speed', 'Gait Speed', 'activity-and-behavior')
ON CONFLICT (id) DO NOTHING;

-- Insert data into public.global_variable_relationships
INSERT INTO public."global_variable_relationships" ("absolute_change_unit_id", "absolute_change_value", "baseline_description", "category", "citation_id", "finding_specific_notes", "is_positive_outcome", "nnh", "nnt", "outcome_global_variable_id", "percentage_change", "predictor_global_variable_id")
VALUES
  ('milligrams-per-deciliter', -10, '(baseline: 150 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Metformin is expected to lower fasting blood glucose.', TRUE, 9999, 4, 'fasting-blood-glucose', -6.67, 'metformin'),
  ('percent', -0.7, '(baseline: 7.5%)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Metformin is expected to lower HbA1c levels.', TRUE, 9999, 5, 'hba1c', -9.33, 'metformin'),
  ('kilogram', -2.5, '(baseline: 90 kg)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Metformin may contribute to modest weight loss.', TRUE, 9999, 10, 'body-weight', -2.78, 'metformin'),
  ('centimeter', -2, '(baseline: 100 cm)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Metformin may lead to a small reduction in waist circumference.', TRUE, 9999, 12, 'waist-circumference', -2, 'metformin'),
  ('per-microliter', -2, '(baseline: 15 μU/mL)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Metformin can decrease fasting insulin levels.', TRUE, 9999, 6, 'fasting-insulin', -13.33, 'metformin'),
  ('milligrams-per-deciliter', -15, '(baseline: 170 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Metformin can reduce triglyceride levels.', TRUE, 9999, 7, 'triglycerides', -8.82, 'metformin'),
  ('milligrams-per-deciliter', 2, '(baseline: 45 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Metformin may slightly increase HDL cholesterol.', TRUE, 9999, 15, 'hdl-cholesterol', 4.44, 'metformin'),
  ('milligrams-per-deciliter', -5, '(baseline: 120 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Metformin may modestly reduce LDL cholesterol.', TRUE, 9999, 11, 'ldl-cholesterol', -4.17, 'metformin'),
  ('dimensionless-unit', -0.5, '(baseline: 3.0)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Metformin improves insulin resistance as measured by HOMA-IR.', TRUE, 9999, 5, 'insulin-resistance-homa-ir', -16.67, 'metformin'),
  ('milligram', 1500, '(baseline: 500 mg/day)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Dosage may be titrated up based on efficacy and tolerability.', FALSE, 9999, 9999, 'metformin-dosage', 300, 'metformin'),
  ('one-to-five-scale', 2, '(baseline: 0, no side effects)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Gastrointestinal side effects are common with metformin.', FALSE, 5, 9999, 'gastrointestinal-side-effects', 40, 'metformin'),
  ('millimeters-of-mercury', -10, '(baseline: 140 mmHg)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Lisinopril lowers systolic blood pressure.', TRUE, 9999, 5, 'systolic-blood-pressure', -7, 'lisinopril'),
  ('millimeters-of-mercury', -5, '(baseline: 90 mmHg)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Lisinopril lowers diastolic blood pressure.', TRUE, 9999, 8, 'diastolic-blood-pressure', -5.5, 'lisinopril'),
  ('milligrams-per-deciliter', 0.1, '(baseline: 1.0 mg/dL)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Lisinopril may slightly increase blood creatinine.', FALSE, 50, 9999, 'blood-creatinine', 10, 'lisinopril'),
  ('millimoles-per-liter', 0.2, '(baseline: 4.0 mmol/L)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Lisinopril may slightly increase blood potassium.', FALSE, 30, 9999, 'blood-potassium', 5, 'lisinopril'),
  ('milligrams-per-deciliter', 2, '(baseline: 20 mg/dL)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Lisinopril may slightly increase BUN.', FALSE, 70, 9999, 'blood-urea-nitrogen-bun', 10, 'lisinopril'),
  ('milligrams-per-deciliter', 0.5, '(baseline: 5.0 mg/dL)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Lisinopril may slightly increase uric acid.', FALSE, 90, 9999, 'uric-acid', 10, 'lisinopril'),
  ('dimensionless-unit', 0.01, '(incidence: 1%)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Lisinopril can cause edema.', FALSE, 200, 9999, 'edema-swelling', 1, 'lisinopril'),
  ('dimensionless-unit', 0.05, '(incidence: 2%)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Lisinopril can cause cough.', FALSE, 50, 9999, 'cough', 2.5, 'lisinopril'),
  ('dimensionless-unit', 0.03, '(incidence: 1%)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Lisinopril can cause dizziness.', FALSE, 100, 9999, 'dizziness', 3, 'lisinopril'),
  ('milliliter', -100, '(baseline: 1500 mL/day)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Lisinopril may slightly reduce urine output.', FALSE, 200, 9999, 'urine-output', -6.67, 'lisinopril'),
  ('dimensionless-unit', -3.5, '(baseline: 12 swollen joints)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Adalimumab reduces swollen joint count in rheumatoid arthritis.', TRUE, 9999, 3, 'swollen-joint-count', -29.17, 'adalimumab'),
  ('dimensionless-unit', -4.2, '(baseline: 15 tender joints)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Adalimumab reduces tender joint count.', TRUE, 9999, 4, 'tender-joint-count', -28, 'adalimumab'),
  ('milligrams-per-deciliter', -25, '(baseline: 35 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Adalimumab lowers CRP levels.', TRUE, 9999, 2, 'crp-c-reactive-protein', -71.43, 'adalimumab'),
  ('millimeter', -20, '(baseline: 40 mm/hr)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Adalimumab lowers ESR.', TRUE, 9999, 3, 'esr-erythrocyte-sedimentation-rate', -50, 'adalimumab'),
  ('dimensionless-unit', -2.5, '(baseline: 5.5)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Adalimumab improves DAS28 score.', TRUE, 9999, 4, 'das28-disease-activity-score-28', -45.45, 'adalimumab'),
  ('one-to-ten-scale', -3, '(baseline: 7)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Adalimumab reduces pain.', TRUE, 9999, 3, 'pain-score', -42.86, 'adalimumab'),
  ('one-to-ten-scale', -2, '(baseline: 6)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Adalimumab reduces fatigue.', TRUE, 9999, 5, 'fatigue-score', -33.33, 'adalimumab'),
  ('zero-to-ten-scale', -1.2, '(baseline: 2.1)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Adalimumab improves HAQ-DI score.', TRUE, 9999, 4, 'haq-di-health-assessment-questionnaire-disability-index', -57.14, 'adalimumab'),
  ('dimensionless-unit', 15, '(baseline: 45)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Adalimumab improves SF-36 physical component summary.', TRUE, 9999, 5, 'sf-36-short-form-36-health-survey', 33.33, 'adalimumab'),
  ('per-month', -1.5, '(baseline: 2 flares/month)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Adalimumab reduces flare frequency.', TRUE, 9999, 3, 'flare-frequency', -75, 'adalimumab'),
  ('one-to-ten-scale', -2.5, '(baseline: 6.5 on HAM-D)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Escitalopram is expected to reduce depression severity.', TRUE, 9999, 4, 'depression-severity', -38.5, 'escitalopram'),
  ('one-to-ten-scale', -2, '(baseline: 7.0 on HAM-A)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Escitalopram can also alleviate anxiety symptoms.', TRUE, 9999, 5, 'anxiety-severity', -28.6, 'escitalopram'),
  ('one-to-ten-scale', 1.5, '(baseline: 4.5 on PSQI)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Improved sleep quality is often observed with escitalopram.', TRUE, 9999, 7, 'sleep-quality', 33.3, 'escitalopram'),
  ('one-to-ten-scale', 2, '(baseline: 5.0 on EQ-5D)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Escitalopram treatment can lead to better overall quality of life.', TRUE, 9999, 6, 'quality-of-life', 40, 'escitalopram'),
  ('percent', 15, '(vs. placebo)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Some patients experience mild side effects like nausea or insomnia.', FALSE, 10, 9999, 'side-effects', 15, 'escitalopram'),
  ('percent', -5, '(baseline: 2% incidence)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Suicidal ideation may decrease with treatment, but monitoring is crucial.', TRUE, 9999, 20, 'suicidal-ideation', -250, 'escitalopram'),
  ('percent', 20, '(baseline: 70%)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Higher treatment adherence is associated with better outcomes.', TRUE, 9999, 9999, 'treatment-adherence', 28.6, 'escitalopram'),
  ('milligram', 10, '(initial dose: 10mg)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Dosage may be adjusted based on individual response and tolerability.', FALSE, 9999, 9999, 'escitalopram-dosage', 100, 'escitalopram'),
  ('liter', 0.5, '(baseline: 2.5 L)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Albuterol is expected to increase peak expiratory flow.', TRUE, 9999, 4, 'peak-expiratory-flow-pef', 20, 'albuterol'),
  ('per-minute', -2, '(baseline: 20 breaths/min)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Albuterol may slightly reduce respiratory rate.', TRUE, 9999, 10, 'respiratory-rate', -10, 'albuterol'),
  ('millimeters-of-mercury', 5, '(baseline: 70 mmHg)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Albuterol can improve oxygenation.', TRUE, 9999, 7, 'partial-pressure-of-oxygen-pao2', 7, 'albuterol'),
  ('percent', 3, '(baseline: 92%)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Albuterol is expected to increase oxygen saturation.', TRUE, 9999, 5, 'oxygen-saturation-spo2', 3, 'albuterol'),
  ('liter', 0.3, '(baseline: 2.2 L)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Albuterol should improve FEV1.', TRUE, 9999, 3, 'forced-expiratory-volume-in-1-second-fev1', 14, 'albuterol'),
  ('per-day', -0.5, '(baseline: 2 episodes/day)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Albuterol is expected to reduce wheezing episodes.', TRUE, 9999, 6, 'wheezing-episodes', -25, 'albuterol'),
  ('one-to-ten-scale', -2, '(baseline: 6/10)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Albuterol should decrease dyspnea score.', TRUE, 9999, 4, 'dyspnea-score', -33, 'albuterol'),
  ('per-day', -1, '(baseline: 2 uses/day)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Albuterol may reduce the need for rescue inhaler use.', TRUE, 9999, 5, 'rescue-inhaler-use', -50, 'albuterol'),
  ('milligram', 2, '(baseline: 4 mg)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Albuterol dosage may be adjusted based on response.', FALSE, 9999, 9999, 'albuterol-dosage', 50, 'albuterol'),
  ('day', -0.5, '(baseline: 2 days)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Albuterol may reduce hospitalization days.', TRUE, 9999, 8, 'hospitalization-days', -25, 'albuterol'),
  ('per-month', -0.2, '(baseline: 1 visit/month)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Albuterol may reduce emergency room visits.', TRUE, 9999, 12, 'emergency-room-visits', -20, 'albuterol'),
  ('kilogram', -10.5, '(Baseline: 95 kg)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide is associated with significant weight loss.', TRUE, 9999, 3, 'body-weight', -11.1, 'semaglutide'),
  ('percent', -5.2, '(Baseline: 30%)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide reduces body fat percentage.', TRUE, 9999, 4, 'body-fat-percentage', -17.3, 'semaglutide'),
  ('centimeter', -8.7, '(Baseline: 105 cm)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide decreases waist circumference.', TRUE, 9999, 3, 'waist-circumference', -8.3, 'semaglutide'),
  ('milligrams-per-deciliter', -25.4, '(Baseline: 120 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide improves fasting blood glucose levels.', TRUE, 9999, 5, 'fasting-blood-glucose', -21.2, 'semaglutide'),
  ('percent', -1.2, '(Baseline: 7.5%)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide lowers HbA1c levels.', TRUE, 9999, 4, 'hba1c', -16, 'semaglutide'),
  ('milligrams-per-deciliter', -12.3, '(Baseline: 130 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide may reduce LDL cholesterol.', TRUE, 9999, 7, 'ldl-cholesterol', -9.5, 'semaglutide'),
  ('milligrams-per-deciliter', 3.1, '(Baseline: 45 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide may slightly increase HDL cholesterol.', TRUE, 9999, 9, 'hdl-cholesterol', 6.9, 'semaglutide'),
  ('millimeters-of-mercury', -4.8, '(Baseline: 135 mmHg)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide may modestly reduce systolic blood pressure.', TRUE, 9999, 8, 'systolic-blood-pressure', -3.6, 'semaglutide'),
  ('millimeters-of-mercury', -2.6, '(Baseline: 85 mmHg)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide may slightly reduce diastolic blood pressure.', TRUE, 9999, 10, 'diastolic-blood-pressure', -3.1, 'semaglutide'),
  ('kilocalorie', -500, '(Baseline: 2500 kcal)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide reduces caloric intake by decreasing appetite.', TRUE, 9999, 2, 'caloric-intake', -20, 'semaglutide'),
  ('one-to-ten-scale', -3, '(Baseline: 7/10)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Semaglutide suppresses appetite.', TRUE, 9999, 2, 'appetite-level', -42.9, 'semaglutide'),
  ('one-to-ten-scale', -2.5, '(baseline: 6.5)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ketamine may reduce depression severity.', TRUE, 9999, 4, 'depression-severity', -38.5, 'ketamine'),
  ('one-to-ten-scale', -3, '(baseline: 7)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ketamine may decrease suicidal ideation.', TRUE, 9999, 3, 'suicidal-ideation', -42.9, 'ketamine'),
  ('one-to-ten-scale', -2, '(baseline: 6)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ketamine may reduce anxiety symptoms.', TRUE, 9999, 5, 'anxiety-symptoms', -33.3, 'ketamine'),
  ('one-to-ten-scale', -3, '(baseline: 7)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ketamine may decrease pain levels.', TRUE, 9999, 3, 'pain-level', -42.9, 'ketamine'),
  ('one-to-ten-scale', 2, '(baseline: 5)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ketamine may improve quality of life.', TRUE, 9999, 4, 'quality-of-life', 40, 'ketamine'),
  ('week', 4, '(baseline: 8 weeks)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ketamine may increase time to relapse.', TRUE, 9999, 6, 'time-to-relapse', 50, 'ketamine'),
  ('micrograms-per-cubic-meter', 200, '(vs. placebo)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Ketamine plasma concentration increases after administration.', FALSE, 9999, 9999, 'ketamine-plasma-concentration', 100, 'ketamine'),
  ('one-to-five-scale', 1, '(vs. placebo)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Ketamine may cause some side effects.', FALSE, 10, 9999, 'side-effects', 20, 'ketamine'),
  ('one-to-ten-scale', 4, '(vs. placebo)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Ketamine may induce dissociative symptoms.', FALSE, 5, 9999, 'dissociative-symptoms', 40, 'ketamine'),
  ('hour', 1, '(vs. placebo)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Ketamine''s effect may last for a certain duration.', TRUE, 9999, 9999, 'duration-of-effect', 50, 'ketamine'),
  ('milligram', -20, '(baseline: 150 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may reduce C-reactive protein levels.', TRUE, 9999, 5, 'c-reactive-protein-crp', -13.3, 'tocilizumab'),
  ('microgram', -500, '(baseline: 1000 µg/L)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may reduce ferritin levels.', TRUE, 9999, 3, 'ferritin', -50, 'tocilizumab'),
  ('percent', -5, '(vs. standard care)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may reduce mortality.', TRUE, 9999, 10, 'mortality', -5, 'tocilizumab'),
  ('day', -2, '(baseline: 10 days)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may shorten hospital length of stay.', TRUE, 9999, 7, 'hospital-length-of-stay', -20, 'tocilizumab'),
  ('percent', -10, '(vs. standard care)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may reduce the need for mechanical ventilation.', TRUE, 9999, 8, 'need-for-mechanical-ventilation', -10, 'tocilizumab'),
  ('percent', 2, '(baseline: 90%)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may improve oxygen saturation.', TRUE, 9999, 12, 'oxygen-saturation-spo2', 2.2, 'tocilizumab'),
  ('one-to-ten-scale', -1, '(baseline: 5/10)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may reduce pain scores.', TRUE, 9999, 15, 'pain-score', -20, 'tocilizumab'),
  ('celsius', -0.5, '(baseline: 38°C)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may reduce body temperature.', TRUE, 9999, 20, 'body-temperature', -1.3, 'tocilizumab'),
  ('per-minute', -2, '(baseline: 22 breaths/min)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may reduce respiratory rate.', TRUE, 9999, 11, 'respiratory-rate', -9.1, 'tocilizumab'),
  ('millimeters-of-mercury', 5, '(baseline: 120 mmHg)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may slightly increase systolic blood pressure.', FALSE, 9999, 9999, 'systolic-blood-pressure', 4.2, 'tocilizumab'),
  ('milligrams-per-deciliter', -0.5, '(baseline: 1.0 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab may reduce D-dimer levels.', TRUE, 9999, 6, 'd-dimer', -50, 'tocilizumab'),
  ('milligrams-per-deciliter', -100, '(baseline: 200 mg/dL)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Tocilizumab inhibits IL-6 signaling, leading to a decrease in IL-6 levels.', TRUE, 9999, 9999, 'interleukin-6-il-6', -50, 'tocilizumab'),
  ('milligram', 100, '(baseline: varies)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Aspirin inhibits COX-1, reducing thromboxane A2 production.', TRUE, 9999, 9999, 'aspirin-dosage', 0, 'aspirin'),
  ('millimeters-of-mercury', -5, '(vs. placebo)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Modest reduction in systolic blood pressure.', TRUE, 9999, 200, 'systolic-blood-pressure', -2, 'aspirin'),
  ('millimeters-of-mercury', -3, '(vs. placebo)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Slight reduction in diastolic blood pressure.', TRUE, 9999, 300, 'diastolic-blood-pressure', -1, 'aspirin'),
  ('percent', -90, '(baseline: pre-treatment levels)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Significant inhibition of platelet aggregation.', TRUE, 9999, 9999, 'platelet-aggregation', -90, 'aspirin'),
  ('percent', 50, '(vs. placebo)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Increased risk of bleeding events.', FALSE, 50, 9999, 'bleeding-events', 50, 'aspirin'),
  ('percent', -20, '(vs. placebo)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Reduced risk of myocardial infarction.', TRUE, 9999, 50, 'myocardial-infarction-heart-attack', -20, 'aspirin'),
  ('percent', -15, '(vs. placebo)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Reduced risk of stroke.', TRUE, 9999, 75, 'stroke', -15, 'aspirin'),
  ('one-to-ten-scale', 2, '(baseline: no headache)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Mild headache pain may occur.', FALSE, 20, 9999, 'headache-pain', 200, 'aspirin'),
  ('milligrams-per-deciliter', 10, '(baseline: 0 mg/dL)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Increased salicylate levels in the blood.', TRUE, 9999, 9999, 'salicylate-level', 1000, 'aspirin'),
  ('one-to-ten-scale', -2.5, '(baseline: 7/10)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ibuprofen is expected to reduce pain levels.', TRUE, 9999, 3, 'pain-level', -35.7, 'ibuprofen'),
  ('celsius', -0.5, '(baseline: 38.5°C)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ibuprofen may reduce body temperature, but not significantly.', TRUE, 9999, 9999, 'body-temperature', -1.3, 'ibuprofen'),
  ('millimeters-of-mercury', -2, '(vs. placebo)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Ibuprofen may not directly affect blood pressure, but studies might show minor correlations.', FALSE, 9999, 9999, 'blood-pressure', -1.5, 'ibuprofen'),
  ('centimeter', -1, '(baseline: 5cm)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ibuprofen can reduce swelling.', TRUE, 9999, 5, 'swelling-diameter', -20, 'ibuprofen'),
  ('hour', -3, '(baseline: 8 hours)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ibuprofen can shorten pain duration.', TRUE, 9999, 4, 'pain-duration', -37.5, 'ibuprofen'),
  ('one-to-ten-scale', -3, '(baseline: 6/10)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Ibuprofen is effective in reducing headache severity.', TRUE, 9999, 2, 'headache-severity', -50, 'ibuprofen'),
  ('milligram', 0, 'N/A', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'This represents the dosage of ibuprofen administered, not an outcome.', FALSE, 9999, 9999, 'ibuprofen-dosage', 0, 'ibuprofen'),
  ('per-day', 0, 'N/A', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'This represents the frequency of ibuprofen use, not a direct outcome.', FALSE, 9999, 9999, 'frequency-of-ibuprofen-use', 0, 'ibuprofen'),
  ('dimensionless-unit', 1, '(vs. placebo)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Some side effects might occur.', FALSE, 200, 9999, 'side-effects', 2, 'ibuprofen'),
  ('percent', -0.5, '(Baseline: 7.5%)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Sitagliptin is expected to reduce HbA1c levels.', TRUE, 9999, 20, 'hba1c', -0.5, 'sitagliptin'),
  ('milligrams-per-deciliter', -15, '(Baseline: 150 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Sitagliptin may reduce fasting plasma glucose levels.', TRUE, 9999, 15, 'fasting-plasma-glucose', -10, 'sitagliptin'),
  ('milligrams-per-deciliter', -20, '(Baseline: 200 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Sitagliptin may reduce postprandial glucose levels.', TRUE, 9999, 25, 'postprandial-glucose', -10, 'sitagliptin'),
  ('kilogram', -1, '(Baseline: 90 kg)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Minor weight loss may be observed with Sitagliptin, but it''s not a primary effect.', TRUE, 9999, 9999, 'body-weight', -1, 'sitagliptin'),
  ('centimeter', -1, '(Baseline: 100 cm)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Slight reduction in waist circumference may occur, but not a primary outcome.', TRUE, 9999, 9999, 'waist-circumference', -1, 'sitagliptin'),
  ('millimeters-of-mercury', -2, '(Baseline: 130 mmHg)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Minimal impact on systolic blood pressure is expected.', TRUE, 9999, 9999, 'systolic-blood-pressure', -1.5, 'sitagliptin'),
  ('millimeters-of-mercury', -1, '(Baseline: 80 mmHg)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Minimal impact on diastolic blood pressure is expected.', TRUE, 9999, 9999, 'diastolic-blood-pressure', -1.25, 'sitagliptin'),
  ('per-week', 0.1, '(Baseline: 0.5 episodes/week)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Slight increase in hypoglycemia episodes might be observed.', FALSE, 50, 9999, 'hypoglycemia-episodes', 20, 'sitagliptin'),
  ('percent', 5, '(Baseline: 70%)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Medication adherence may improve slightly due to reduced side effects compared to some alternatives.', TRUE, 9999, 9999, 'medication-adherence', 7, 'sitagliptin'),
  ('one-to-ten-scale', -2.5, '(baseline: 6.5)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Venlafaxine is expected to reduce depression severity.', TRUE, 9999, 4, 'depression-severity', -38.5, 'venlafaxine'),
  ('one-to-ten-scale', -2, '(baseline: 7.0)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Venlafaxine can also reduce anxiety severity.', TRUE, 9999, 5, 'anxiety-severity', -28.6, 'venlafaxine'),
  ('one-to-ten-scale', 1.5, '(baseline: 4.5)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Improved quality of life is expected with venlafaxine treatment.', TRUE, 9999, 6, 'quality-of-life', 33.3, 'venlafaxine'),
  ('per-week', -3.2, '(baseline: 5 attacks/week)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Venlafaxine should reduce the frequency of panic attacks.', TRUE, 9999, 3, 'frequency-of-panic-attacks', -64, 'venlafaxine'),
  ('milligram', 75, '(initial dose: 37.5mg)', 'Mechanism', 'cite-models-gemini-1-5-pro-latest', 'Dosage may be adjusted based on individual response and tolerability.', FALSE, 9999, 9999, 'venlafaxine-dosage', 200, 'venlafaxine'),
  ('one-to-five-scale', 1.2, '(vs. placebo)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Some patients experience mild to moderate side effects.', FALSE, 10, 9999, 'side-effects-severity', 24, 'venlafaxine'),
  ('one-to-five-scale', 0.8, '(baseline: 2.5)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Sleep quality may improve with reduced anxiety and depression.', TRUE, 9999, 9999, 'sleep-quality', 32, 'venlafaxine'),
  ('kilogram', 2.5, '(vs. placebo)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Weight gain is a potential side effect.', FALSE, 20, 9999, 'weight', 3, 'venlafaxine'),
  ('millimeters-of-mercury', 2, '(vs. placebo)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Small increases in blood pressure are possible.', FALSE, 50, 9999, 'blood-pressure', 1.5, 'venlafaxine'),
  ('per-minute', 5, '(vs. placebo)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Slight increase in heart rate is sometimes observed.', FALSE, 30, 9999, 'heart-rate', 6, 'venlafaxine'),
  ('milligrams-per-deciliter', -20, '(Baseline: 150 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Atorvastatin 20mg reduces LDL cholesterol.', TRUE, 9999, 5, 'ldl-cholesterol', -13.3, 'atorvastatin-20mg'),
  ('milligrams-per-deciliter', 5, '(Baseline: 45 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Atorvastatin 20mg increases HDL cholesterol.', TRUE, 9999, 20, 'hdl-cholesterol', 11.1, 'atorvastatin-20mg'),
  ('milligrams-per-deciliter', -25, '(Baseline: 200 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Atorvastatin 20mg reduces total cholesterol.', TRUE, 9999, 4, 'total-cholesterol', -12.5, 'atorvastatin-20mg'),
  ('milligrams-per-deciliter', -15, '(Baseline: 180 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Atorvastatin 20mg may reduce triglycerides.', TRUE, 9999, 12, 'triglycerides', -8.3, 'atorvastatin-20mg'),
  ('millimeters-of-mercury', -5, '(Baseline: 130 mmHg)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Atorvastatin''s effect on blood pressure is minimal.', TRUE, 9999, 9999, 'systolic-blood-pressure', -3.8, 'atorvastatin-20mg'),
  ('millimeters-of-mercury', -2, '(Baseline: 80 mmHg)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Atorvastatin''s effect on blood pressure is minimal.', TRUE, 9999, 9999, 'diastolic-blood-pressure', -2.5, 'atorvastatin-20mg'),
  ('percent', -20, '(vs. placebo)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Atorvastatin 20mg reduces the risk of cardiovascular events.', TRUE, 9999, 8, 'cardiovascular-events', -20, 'atorvastatin-20mg'),
  ('dimensionless-unit', 1.5, '(Baseline: 1.0 x ULN)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Atorvastatin can slightly increase creatine kinase levels.', FALSE, 500, 9999, 'creatine-kinase-ck', 150, 'atorvastatin-20mg'),
  ('dimensionless-unit', 1.2, '(Baseline: 1.0 x ULN)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Atorvastatin can slightly increase liver enzyme levels.', FALSE, 200, 9999, 'liver-function-tests', 120, 'atorvastatin-20mg'),
  ('one-to-ten-scale', 1, '(Baseline: 0)', 'Safety', 'cite-models-gemini-1-5-pro-latest', 'Atorvastatin can cause muscle symptoms.', FALSE, 100, 9999, 'muscle-symptoms', 0, 'atorvastatin-20mg'),
  ('year', 2.5, '(baseline: 75 years)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Klotho therapy may increase lifespan by upregulating anti-aging pathways.', TRUE, 9999, 5, 'lifespan', 3.3, 'klotho-therapy'),
  ('year', 3, '(baseline: 65 years)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Improved healthspan due to delayed onset of age-related diseases.', TRUE, 9999, 4, 'healthspan', 4.6, 'klotho-therapy'),
  ('dimensionless-unit', -0.05, '(baseline: 0.25)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Reduced frailty due to improved physiological function.', TRUE, 9999, 7, 'frailty-index', -20, 'klotho-therapy'),
  ('milligrams-per-deciliter', -10, '(baseline: 110 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Improved glucose metabolism.', TRUE, 9999, 6, 'fasting-blood-glucose', -9.1, 'klotho-therapy'),
  ('percent', -0.5, '(baseline: 6%)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Improved glycemic control.', TRUE, 9999, 8, 'hba1c', -8.3, 'klotho-therapy'),
  ('millimeters-of-mercury', -5, '(baseline: 130 mmHg)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Slight reduction in systolic blood pressure.', TRUE, 9999, 10, 'systolic-blood-pressure', -3.8, 'klotho-therapy'),
  ('millimeters-of-mercury', -3, '(baseline: 80 mmHg)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Slight reduction in diastolic blood pressure.', TRUE, 9999, 12, 'diastolic-blood-pressure', -3.8, 'klotho-therapy'),
  ('milligrams-per-deciliter', -0.1, '(baseline: 1.2 mg/dL)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Improved kidney function.', TRUE, 9999, 9, 'creatinine', -8.3, 'klotho-therapy'),
  ('milliliter', 5, '(baseline: 85 mL/min)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Improved kidney filtration rate.', TRUE, 9999, 7, 'estimated-glomerular-filtration-rate-egfr', 5.9, 'klotho-therapy'),
  ('dimensionless-unit', 2, '(baseline: 25)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Improved cognitive performance.', TRUE, 9999, 6, 'cognitive-function-score', 8, 'klotho-therapy'),
  ('second', -0.1, '(baseline: 0.8 seconds)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Faster reaction time.', TRUE, 9999, 8, 'reaction-time', -12.5, 'klotho-therapy'),
  ('kilogram', 1, '(baseline: 25 kg)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Increased grip strength.', TRUE, 9999, 5, 'grip-strength', 4, 'klotho-therapy'),
  ('meter', 0.1, '(baseline: 1.0 m/s)', 'Efficacy', 'cite-models-gemini-1-5-pro-latest', 'Increased gait speed.', TRUE, 9999, 6, 'gait-speed', 10, 'klotho-therapy'),
  ('kilogram', -1, '(baseline: 75 kg)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Potential slight decrease in body weight.', TRUE, 9999, 9999, 'body-weight', -1.3, 'klotho-therapy'),
  ('percent', -2, '(baseline: 25%)', 'Correlation', 'cite-models-gemini-1-5-pro-latest', 'Potential slight reduction in body fat percentage.', TRUE, 9999, 9999, 'body-fat-percentage', -8, 'klotho-therapy');

