/**
 * Zod schemas for validating rows before they are written: AI-generated
 * variables, relationships and citations.
 *
 * This file is maintained by hand (it was generated by supazod from the old
 * Supabase types). Keep each schema in step with prisma/schema.prisma. Enum
 * schemas come from the generated Prisma enums, so they follow the database.
 * Timestamps are ISO-8601 strings, which Prisma accepts for DateTime columns.
 */
import { z } from "zod";
import {
  citation_type,
  evidence_certainty_enum,
  relationship_category_enum,
} from "@/lib/generated/prisma/enums";

export const publicCitationTypeSchema = z.nativeEnum(citation_type);
export const publicEvidenceCertaintyEnumSchema = z.nativeEnum(evidence_certainty_enum);
export const publicRelationshipCategoryEnumSchema = z.nativeEnum(relationship_category_enum);

export const publicGlobalVariablesInsertSchemaSchema = z.object({
  canonical_global_variable_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  default_unit_id: z.string(),
  deleted_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  emoji: z.string().optional().nullable(),
  id: z.string(),
  image_url: z.string().optional().nullable(),
  name: z.string(),
  updated_at: z.string().optional().nullable(),
  variable_category_id: z.string(),
});

export const publicGlobalVariableRelationshipsInsertSchemaSchema = z.object({
  absolute_change_ci_lower: z.number().optional().nullable(),
  absolute_change_ci_upper: z.number().optional().nullable(),
  absolute_change_unit_id: z.string().optional().nullable(),
  absolute_change_value: z.number().optional().nullable(),
  baseline_description: z.string().optional().nullable(),
  category: publicRelationshipCategoryEnumSchema,
  certainty_of_evidence: publicEvidenceCertaintyEnumSchema.optional().nullable(),
  citation_id: z.string(),
  condition_id: z.string().optional().nullable(),
  confidence_interval_level: z.number().optional().nullable(),
  created_at: z.string().optional(),
  data_last_updated: z.string().optional().nullable(),
  finding_specific_notes: z.string().optional().nullable(),
  id: z.string().optional(),
  is_positive_outcome: z.boolean().optional().nullable(),
  nnh: z.number().optional().nullable(),
  nnt: z.number().optional().nullable(),
  outcome_global_variable_id: z.string(),
  p_value: z.number().optional().nullable(),
  percentage_change: z.number().optional().nullable(),
  percentage_change_ci_lower: z.number().optional().nullable(),
  percentage_change_ci_upper: z.number().optional().nullable(),
  predictor_global_variable_id: z.string(),
  updated_at: z.string().optional(),
});

export const publicCitationsInsertSchemaSchema = z.object({
  abstract: z.string().optional().nullable(),
  aggregate_participant_count: z.number().optional().nullable(),
  aggregate_trial_count: z.number().optional().nullable(),
  authors: z.array(z.string()).optional().nullable(),
  created_at: z.string().optional(),
  doi: z.string().optional().nullable(),
  id: z.string().optional(),
  issue: z.string().optional().nullable(),
  journal_or_publisher: z.string().optional().nullable(),
  pages: z.string().optional().nullable(),
  pmid: z.string().optional().nullable(),
  publication_year: z.number().optional().nullable(),
  retrieved_at: z.string().optional().nullable(),
  title: z.string().optional().nullable(),
  type: publicCitationTypeSchema,
  updated_at: z.string().optional(),
  url: z.string().optional().nullable(),
  volume: z.string().optional().nullable(),
});

