/**
 * Database row, insert and update types, taken from the Prisma schema.
 *
 * This file used to be generated by `supabase gen types`. It now maps the same
 * helper names (`Tables`, `TablesInsert`, `TablesUpdate`, `Enums`, `Database`)
 * onto the types that Prisma generates from `prisma/schema.prisma`, so the
 * shapes match what `lib/db` returns. Timestamps and dates are `Date` objects,
 * `json` columns are `JsonValue`, and money columns are `Prisma.Decimal`.
 *
 * Do not add table definitions here: change the schema, then run
 * `pnpm db:pull` to update `prisma/schema.prisma` and the generated client.
 */
import type { Prisma } from '@/lib/generated/prisma/client'
import * as PrismaEnums from '@/lib/generated/prisma/enums'

type ModelMap = Prisma.TypeMap['model']

type ViewName =
  | 'pending_actions'
  | 'patient_eligible_trials_view'
  | 'patient_conditions_view'
  | 'treatment_ratings_stats'

type TableName = Exclude<keyof ModelMap, ViewName>

type Row<K extends keyof ModelMap> = ModelMap[K]['payload']['scalars']

type OperationData<K extends keyof ModelMap, Op extends string> =
  ModelMap[K]['operations'] extends Record<Op, { args: { data: infer D } }> ? D : never

type EnumObjects = typeof PrismaEnums
type EnumName = keyof EnumObjects

export type Json = Prisma.JsonValue

export type Database = {
  public: {
    Tables: {
      [K in TableName]: {
        Row: Row<K>
        Insert: OperationData<K, 'create'>
        Update: OperationData<K, 'update'>
      }
    }
    Views: {
      [K in ViewName]: {
        Row: Row<K>
      }
    }
    Enums: {
      [K in EnumName]: EnumObjects[K][keyof EnumObjects[K]]
    }
  }
}

export type Tables<K extends TableName | ViewName> = Row<K>
export type TablesInsert<K extends TableName> = Database['public']['Tables'][K]['Insert']
export type TablesUpdate<K extends TableName> = Database['public']['Tables'][K]['Update']
export type Enums<K extends EnumName> = Database['public']['Enums'][K]

/** Enum values as arrays, for select options and validation. */
export const Constants = {
  public: {
    Enums: Object.fromEntries(
      Object.entries(PrismaEnums).map(([name, values]) => [name, Object.values(values)]),
    ) as { [K in EnumName]: Array<EnumObjects[K][keyof EnumObjects[K]]> },
  },
} as const
