// Generated by script at 2025-04-15T17:41:10.395Z
// Source table: public.units
// Do not edit this file manually, it will be overwritten.

import type { Database } from '@/lib/database.types';

type UnitRow = Database['public']['Tables']['units']['Row'];

export const UNIT_IDS = {
  ATMOSPHERE: 'atmosphere', // Atmosphere
  BRITISH_POUND: 'british-pound', // British Pound
  CELSIUS: 'celsius', // Celsius
  CENTIMETER: 'centimeter', // Centimeter
  DAY: 'day', // Day
  DECIBEL: 'decibel', // Decibel
  DECILITER: 'deciliter', // Deciliter
  DIMENSIONLESS: 'dimensionless-unit', // Dimensionless
  EURO: 'euro', // Euro
  FAHRENHEIT: 'fahrenheit', // Fahrenheit
  FOOT: 'foot', // Foot
  GRAM: 'gram', // Gram
  GRAMS_PER_LITER: 'grams-per-liter', // Grams per Liter
  HOUR: 'hour', // Hour
  INCH: 'inch', // Inch
  KILOCALORIE: 'kilocalorie', // Kilocalorie
  KILOGRAM: 'kilogram', // Kilogram
  KILOGRAMS_PER_SQUARE_METER: 'kilograms-per-square-meter', // Kilograms per Square Meter
  KILOJOULE: 'kilojoule', // Kilojoule
  KILOMETER: 'kilometer', // Kilometer
  LITER: 'liter', // Liter
  METER: 'meter', // Meter
  MICROGRAM: 'microgram', // Microgram
  MICROGRAMS_PER_CUBIC_METER: 'micrograms-per-cubic-meter', // Micrograms per Cubic Meter
  MILE: 'mile', // Mile
  MILLIGRAM: 'milligram', // Milligram
  MILLIGRAMS_PER_DECILITER: 'milligrams-per-deciliter', // Milligrams per Deciliter
  MILLILITER: 'milliliter', // Milliliter
  MILLIMETER: 'millimeter', // Millimeter
  MILLIMETERS_OF_MERCURY: 'millimeters-of-mercury', // Millimeters of Mercury
  MILLIMOLES_PER_LITER: 'millimoles-per-liter', // Millimoles per Liter
  MINUTE: 'minute', // Minute
  MONTH: 'month', // Month
  ONE_TO_FIVE_SCALE: 'one-to-five-scale', // One to Five Scale
  ONE_TO_TEN_SCALE: 'one-to-ten-scale', // One to Ten Scale
  PARTS_PER_BILLION: 'parts-per-billion', // Parts Per Billion
  PARTS_PER_MILLION: 'parts-per-million', // Parts Per Million
  PASCAL: 'pascal', // Pascal
  PER_DAY: 'per-day', // Per Day
  PER_MICROLITER: 'per-microliter', // Per Microliter
  PER_MINUTE: 'per-minute', // Per Minute
  PER_MONTH: 'per-month', // Per Month
  PER_SECOND: 'per-second', // Per Second
  PER_WEEK: 'per-week', // Per Week
  PERCENT: 'percent', // Percent
  POUND: 'pound', // Pound
  SECOND: 'second', // Second
  US_DOLLAR: 'us-dollar', // US Dollar
  WEEK: 'week', // Week
  YEAR: 'year', // Year
  YEARS_AGE_: 'year-age', // Years (age)
  ZERO_TO_TEN_SCALE: 'zero-to-ten-scale', // Zero to Ten Scale
} as const;

export const UNITS_DATA: Record<string, Partial<UnitRow>> = {
  [UNIT_IDS.ATMOSPHERE]: {
  "id": "atmosphere",
  "unit_category_id": "pressure",
  "name": "Atmosphere",
  "abbreviated_name": "atm",
  "ucum_code": "atm",
  "conversion_factor": 0.00000986923,
  "conversion_offset": 0,
  "emoji": "💨"
},
  [UNIT_IDS.BRITISH_POUND]: {
  "id": "british-pound",
  "unit_category_id": "currency",
  "name": "British Pound",
  "abbreviated_name": "GBP",
  "ucum_code": "[GBP]",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "💰"
},
  [UNIT_IDS.CELSIUS]: {
  "id": "celsius",
  "unit_category_id": "temperature",
  "name": "Celsius",
  "abbreviated_name": "°C",
  "ucum_code": "Cel",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🌡️"
},
  [UNIT_IDS.CENTIMETER]: {
  "id": "centimeter",
  "unit_category_id": "length",
  "name": "Centimeter",
  "abbreviated_name": "cm",
  "ucum_code": "cm",
  "conversion_factor": 100,
  "conversion_offset": 0,
  "emoji": "📏"
},
  [UNIT_IDS.DAY]: {
  "id": "day",
  "unit_category_id": "time",
  "name": "Day",
  "abbreviated_name": "d",
  "ucum_code": "d",
  "conversion_factor": 0.0000115741,
  "conversion_offset": 0,
  "emoji": "⏱️"
},
  [UNIT_IDS.DECIBEL]: {
  "id": "decibel",
  "unit_category_id": "noise",
  "name": "Decibel",
  "abbreviated_name": "dB",
  "ucum_code": "dB",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🔊"
},
  [UNIT_IDS.DECILITER]: {
  "id": "deciliter",
  "unit_category_id": "volume",
  "name": "Deciliter",
  "abbreviated_name": "dL",
  "ucum_code": "dL",
  "conversion_factor": 10,
  "conversion_offset": 0,
  "emoji": "💧"
},
  [UNIT_IDS.DIMENSIONLESS]: {
  "id": "dimensionless-unit",
  "unit_category_id": "dimensionless",
  "name": "Dimensionless",
  "abbreviated_name": "1",
  "ucum_code": "1",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🔢"
},
  [UNIT_IDS.EURO]: {
  "id": "euro",
  "unit_category_id": "currency",
  "name": "Euro",
  "abbreviated_name": "EUR",
  "ucum_code": "[EUR]",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "💰"
},
  [UNIT_IDS.FAHRENHEIT]: {
  "id": "fahrenheit",
  "unit_category_id": "temperature",
  "name": "Fahrenheit",
  "abbreviated_name": "°F",
  "ucum_code": "[degF]",
  "conversion_factor": 1.8,
  "conversion_offset": 32,
  "emoji": "🌡️"
},
  [UNIT_IDS.FOOT]: {
  "id": "foot",
  "unit_category_id": "length",
  "name": "Foot",
  "abbreviated_name": "ft",
  "ucum_code": "[ft_i]",
  "conversion_factor": 3.28084,
  "conversion_offset": 0,
  "emoji": "📏"
},
  [UNIT_IDS.GRAM]: {
  "id": "gram",
  "unit_category_id": "weight",
  "name": "Gram",
  "abbreviated_name": "g",
  "ucum_code": "g",
  "conversion_factor": 1000,
  "conversion_offset": 0,
  "emoji": "⚖️"
},
  [UNIT_IDS.GRAMS_PER_LITER]: {
  "id": "grams-per-liter",
  "unit_category_id": "concentration",
  "name": "Grams per Liter",
  "abbreviated_name": "g/L",
  "ucum_code": "g/L",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🧪"
},
  [UNIT_IDS.HOUR]: {
  "id": "hour",
  "unit_category_id": "time",
  "name": "Hour",
  "abbreviated_name": "h",
  "ucum_code": "h",
  "conversion_factor": 0.000277778,
  "conversion_offset": 0,
  "emoji": "⏱️"
},
  [UNIT_IDS.INCH]: {
  "id": "inch",
  "unit_category_id": "length",
  "name": "Inch",
  "abbreviated_name": "in",
  "ucum_code": "[in_i]",
  "conversion_factor": 39.3701,
  "conversion_offset": 0,
  "emoji": "📏"
},
  [UNIT_IDS.KILOCALORIE]: {
  "id": "kilocalorie",
  "unit_category_id": "energy",
  "name": "Kilocalorie",
  "abbreviated_name": "kcal",
  "ucum_code": "kcal",
  "conversion_factor": 0.239006,
  "conversion_offset": 0,
  "emoji": "⚡"
},
  [UNIT_IDS.KILOGRAM]: {
  "id": "kilogram",
  "unit_category_id": "weight",
  "name": "Kilogram",
  "abbreviated_name": "kg",
  "ucum_code": "kg",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "⚖️"
},
  [UNIT_IDS.KILOGRAMS_PER_SQUARE_METER]: {
  "id": "kilograms-per-square-meter",
  "unit_category_id": "dimensionless",
  "name": "Kilograms per Square Meter",
  "abbreviated_name": "kg/m2",
  "ucum_code": "kg/m2",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "📊"
},
  [UNIT_IDS.KILOJOULE]: {
  "id": "kilojoule",
  "unit_category_id": "energy",
  "name": "Kilojoule",
  "abbreviated_name": "kJ",
  "ucum_code": "kJ",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "⚡"
},
  [UNIT_IDS.KILOMETER]: {
  "id": "kilometer",
  "unit_category_id": "length",
  "name": "Kilometer",
  "abbreviated_name": "km",
  "ucum_code": "km",
  "conversion_factor": 0.001,
  "conversion_offset": 0,
  "emoji": "📏"
},
  [UNIT_IDS.LITER]: {
  "id": "liter",
  "unit_category_id": "volume",
  "name": "Liter",
  "abbreviated_name": "L",
  "ucum_code": "L",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "💧"
},
  [UNIT_IDS.METER]: {
  "id": "meter",
  "unit_category_id": "length",
  "name": "Meter",
  "abbreviated_name": "m",
  "ucum_code": "m",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "📏"
},
  [UNIT_IDS.MICROGRAM]: {
  "id": "microgram",
  "unit_category_id": "weight",
  "name": "Microgram",
  "abbreviated_name": "ug",
  "ucum_code": "ug",
  "conversion_factor": 1000000000,
  "conversion_offset": 0,
  "emoji": "⚖️"
},
  [UNIT_IDS.MICROGRAMS_PER_CUBIC_METER]: {
  "id": "micrograms-per-cubic-meter",
  "unit_category_id": "air-quality",
  "name": "Micrograms per Cubic Meter",
  "abbreviated_name": "µg/m³",
  "ucum_code": "ug/m3",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🌬️"
},
  [UNIT_IDS.MILE]: {
  "id": "mile",
  "unit_category_id": "length",
  "name": "Mile",
  "abbreviated_name": "mi",
  "ucum_code": "[mi_i]",
  "conversion_factor": 0.000621371,
  "conversion_offset": 0,
  "emoji": "📏"
},
  [UNIT_IDS.MILLIGRAM]: {
  "id": "milligram",
  "unit_category_id": "weight",
  "name": "Milligram",
  "abbreviated_name": "mg",
  "ucum_code": "mg",
  "conversion_factor": 1000000,
  "conversion_offset": 0,
  "emoji": "⚖️"
},
  [UNIT_IDS.MILLIGRAMS_PER_DECILITER]: {
  "id": "milligrams-per-deciliter",
  "unit_category_id": "concentration",
  "name": "Milligrams per Deciliter",
  "abbreviated_name": "mg/dL",
  "ucum_code": "mg/dL",
  "conversion_factor": 18.0182,
  "conversion_offset": 0,
  "emoji": "🧪"
},
  [UNIT_IDS.MILLILITER]: {
  "id": "milliliter",
  "unit_category_id": "volume",
  "name": "Milliliter",
  "abbreviated_name": "mL",
  "ucum_code": "mL",
  "conversion_factor": 1000,
  "conversion_offset": 0,
  "emoji": "💧"
},
  [UNIT_IDS.MILLIMETER]: {
  "id": "millimeter",
  "unit_category_id": "length",
  "name": "Millimeter",
  "abbreviated_name": "mm",
  "ucum_code": "mm",
  "conversion_factor": 1000,
  "conversion_offset": 0,
  "emoji": "📏"
},
  [UNIT_IDS.MILLIMETERS_OF_MERCURY]: {
  "id": "millimeters-of-mercury",
  "unit_category_id": "pressure",
  "name": "Millimeters of Mercury",
  "abbreviated_name": "mmHg",
  "ucum_code": "mm[Hg]",
  "conversion_factor": 0.00750062,
  "conversion_offset": 0,
  "emoji": "💨"
},
  [UNIT_IDS.MILLIMOLES_PER_LITER]: {
  "id": "millimoles-per-liter",
  "unit_category_id": "concentration",
  "name": "Millimoles per Liter",
  "abbreviated_name": "mmol/L",
  "ucum_code": "mmol/L",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🧪"
},
  [UNIT_IDS.MINUTE]: {
  "id": "minute",
  "unit_category_id": "time",
  "name": "Minute",
  "abbreviated_name": "min",
  "ucum_code": "min",
  "conversion_factor": 0.0166667,
  "conversion_offset": 0,
  "emoji": "⏱️"
},
  [UNIT_IDS.MONTH]: {
  "id": "month",
  "unit_category_id": "time",
  "name": "Month",
  "abbreviated_name": "mo",
  "ucum_code": "mo",
  "conversion_factor": 3.80517e-7,
  "conversion_offset": 0,
  "emoji": "⏱️"
},
  [UNIT_IDS.ONE_TO_FIVE_SCALE]: {
  "id": "one-to-five-scale",
  "unit_category_id": "dimensionless",
  "name": "One to Five Scale",
  "abbreviated_name": "1-5",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "⑤"
},
  [UNIT_IDS.ONE_TO_TEN_SCALE]: {
  "id": "one-to-ten-scale",
  "unit_category_id": "dimensionless",
  "name": "One to Ten Scale",
  "abbreviated_name": "1-10",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🔟"
},
  [UNIT_IDS.PARTS_PER_BILLION]: {
  "id": "parts-per-billion",
  "unit_category_id": "air-quality",
  "name": "Parts Per Billion",
  "abbreviated_name": "ppb",
  "ucum_code": "ppb",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🌬️"
},
  [UNIT_IDS.PARTS_PER_MILLION]: {
  "id": "parts-per-million",
  "unit_category_id": "air-quality",
  "name": "Parts Per Million",
  "abbreviated_name": "ppm",
  "ucum_code": "ppm",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🌬️"
},
  [UNIT_IDS.PASCAL]: {
  "id": "pascal",
  "unit_category_id": "pressure",
  "name": "Pascal",
  "abbreviated_name": "Pa",
  "ucum_code": "Pa",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "💨"
},
  [UNIT_IDS.PER_DAY]: {
  "id": "per-day",
  "unit_category_id": "frequency",
  "name": "Per Day",
  "abbreviated_name": "/d",
  "ucum_code": "/d",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🔄"
},
  [UNIT_IDS.PER_MICROLITER]: {
  "id": "per-microliter",
  "unit_category_id": "cell-count",
  "name": "Per Microliter",
  "abbreviated_name": "/uL",
  "ucum_code": "/uL",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🔬"
},
  [UNIT_IDS.PER_MINUTE]: {
  "id": "per-minute",
  "unit_category_id": "rate",
  "name": "Per Minute",
  "abbreviated_name": "/min",
  "ucum_code": "/min",
  "conversion_factor": 60,
  "conversion_offset": 0,
  "emoji": "💓"
},
  [UNIT_IDS.PER_MONTH]: {
  "id": "per-month",
  "unit_category_id": "frequency",
  "name": "Per Month",
  "abbreviated_name": "/mo",
  "ucum_code": "/mo",
  "conversion_factor": 0.0328767,
  "conversion_offset": 0,
  "emoji": "🔄"
},
  [UNIT_IDS.PER_SECOND]: {
  "id": "per-second",
  "unit_category_id": "rate",
  "name": "Per Second",
  "abbreviated_name": "/s",
  "ucum_code": "/s",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "💓"
},
  [UNIT_IDS.PER_WEEK]: {
  "id": "per-week",
  "unit_category_id": "frequency",
  "name": "Per Week",
  "abbreviated_name": "/wk",
  "ucum_code": "/wk",
  "conversion_factor": 0.142857,
  "conversion_offset": 0,
  "emoji": "🔄"
},
  [UNIT_IDS.PERCENT]: {
  "id": "percent",
  "unit_category_id": "percentage",
  "name": "Percent",
  "abbreviated_name": "%",
  "ucum_code": "%",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "%"
},
  [UNIT_IDS.POUND]: {
  "id": "pound",
  "unit_category_id": "weight",
  "name": "Pound",
  "abbreviated_name": "lb",
  "ucum_code": "[lb_av]",
  "conversion_factor": 2.20462,
  "conversion_offset": 0,
  "emoji": "⚖️"
},
  [UNIT_IDS.SECOND]: {
  "id": "second",
  "unit_category_id": "time",
  "name": "Second",
  "abbreviated_name": "s",
  "ucum_code": "s",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "⏱️"
},
  [UNIT_IDS.US_DOLLAR]: {
  "id": "us-dollar",
  "unit_category_id": "currency",
  "name": "US Dollar",
  "abbreviated_name": "USD",
  "ucum_code": "[USD]",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "💰"
},
  [UNIT_IDS.WEEK]: {
  "id": "week",
  "unit_category_id": "time",
  "name": "Week",
  "abbreviated_name": "wk",
  "ucum_code": "wk",
  "conversion_factor": 0.00000165344,
  "conversion_offset": 0,
  "emoji": "⏱️"
},
  [UNIT_IDS.YEAR]: {
  "id": "year",
  "unit_category_id": "time",
  "name": "Year",
  "abbreviated_name": "a",
  "ucum_code": "a",
  "conversion_factor": 3.17098e-8,
  "conversion_offset": 0,
  "emoji": "⏱️"
},
  [UNIT_IDS.YEARS_AGE_]: {
  "id": "year-age",
  "unit_category_id": "age",
  "name": "Years (age)",
  "abbreviated_name": "yr",
  "ucum_code": "a",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🎂"
},
  [UNIT_IDS.ZERO_TO_TEN_SCALE]: {
  "id": "zero-to-ten-scale",
  "unit_category_id": "dimensionless",
  "name": "Zero to Ten Scale",
  "abbreviated_name": "0-10",
  "conversion_factor": 1,
  "conversion_offset": 0,
  "emoji": "🔟"
},
};
