// Source table: public.variable_categories
// Do not edit this file manually, it will be overwritten.

import type { Database } from '@/lib/database.types';

type VariableCategory = Database['public']['Tables']['variable_categories']['Row'];

export const VARIABLE_CATEGORY_IDS = {
  HEALTH_AND_PHYSIOLOGY: 'health-and-physiology', // Health and Physiology
  INTAKE_AND_INTERVENTIONS: 'intake-and-interventions', // Intake and Interventions
  ACTIVITY_AND_BEHAVIOR: 'activity-and-behavior', // Activity and Behavior
  MENTAL_AND_EMOTIONAL_STATE: 'mental-and-emotional-state', // Mental and Emotional State
  COGNITIVE_PERFORMANCE: 'cognitive-performance', // Cognitive Performance
  MEDIA_AND_CONTENT_ENGAGEMENT: 'media-and-content-engagement', // Media and Content Engagement
  SOCIAL_AND_INTERPERSONAL: 'social-and-interpersonal', // Social and Interpersonal
  ENVIRONMENT_AND_CONTEXT: 'environment-and-context', // Environment and Context
  PRODUCTIVITY_AND_LEARNING: 'productivity-and-learning', // Productivity and Learning
} as const;

export const VARIABLE_CATEGORIES_DATA: Record<string, Partial<VariableCategory>> = {
  [VARIABLE_CATEGORY_IDS.HEALTH_AND_PHYSIOLOGY]: {
  "id": "health-and-physiology",
  "name": "Health and Physiology",
  "short_description": "Health states and metrics",
  "long_description": "All physical and mental health states and measurements, including symptoms like fatigue, conditions like diabetes, vital signs like heart rate, and biomarkers like blood glucose. Also known as wellness or fitness.",
  "emoji": "🩺",
  "display_order": 1
},
  [VARIABLE_CATEGORY_IDS.INTAKE_AND_INTERVENTIONS]: {
  "id": "intake-and-interventions",
  "name": "Intake and Interventions",
  "short_description": "Substances and actions for health",
  "long_description": "Everything ingested or applied to influence health, such as food (e.g., calories), drinks (e.g., water), supplements (e.g., vitamin D), medications (e.g., aspirin), and procedures (e.g., surgery). Also known as diet or treatment.",
  "emoji": "🍎",
  "display_order": 2
},
  [VARIABLE_CATEGORY_IDS.ACTIVITY_AND_BEHAVIOR]: {
  "id": "activity-and-behavior",
  "name": "Activity and Behavior",
  "short_description": "Actions and habits",
  "long_description": "All actions, movements, and habits performed, including exercise (e.g., steps, sports like tennis), routines (e.g., brushing teeth), and leisure (e.g., painting). Also known as lifestyle or daily activities.",
  "emoji": "🏃",
  "display_order": 3
},
  [VARIABLE_CATEGORY_IDS.MENTAL_AND_EMOTIONAL_STATE]: {
  "id": "mental-and-emotional-state",
  "name": "Mental and Emotional State",
  "short_description": "Feelings and emotions",
  "long_description": "Subjective mental experiences and emotional well-being, such as mood ratings, stress levels, or self-reported energy. Also known as mood or emotional health.",
  "emoji": "😊",
  "display_order": 4
},
  [VARIABLE_CATEGORY_IDS.COGNITIVE_PERFORMANCE]: {
  "id": "cognitive-performance",
  "name": "Cognitive Performance",
  "short_description": "Mental abilities",
  "long_description": "Objective mental abilities and brain function, including memory test scores, reaction times, or IQ scores. Also known as brain performance or cognition.",
  "emoji": "🧠",
  "display_order": 5
},
  [VARIABLE_CATEGORY_IDS.MEDIA_AND_CONTENT_ENGAGEMENT]: {
  "id": "media-and-content-engagement",
  "name": "Media and Content Engagement",
  "short_description": "Content interaction",
  "long_description": "Interaction with informational or entertainment content, such as books read, songs listened to, or shows watched. Also known as media use or consumption.",
  "emoji": "📺",
  "display_order": 6
},
  [VARIABLE_CATEGORY_IDS.SOCIAL_AND_INTERPERSONAL]: {
  "id": "social-and-interpersonal",
  "name": "Social and Interpersonal",
  "short_description": "Relationships and interactions",
  "long_description": "Interactions and relationships with others, including number of conversations, time with friends, or social media chats. Also known as social life or connections.",
  "emoji": "👥",
  "display_order": 7
},
  [VARIABLE_CATEGORY_IDS.ENVIRONMENT_AND_CONTEXT]: {
  "id": "environment-and-context",
  "name": "Environment and Context",
  "short_description": "External and background factors",
  "long_description": "External factors and personal background data, such as air quality, noise levels, age, gender, genetics, or income. Also known as context or surroundings.",
  "emoji": "🌍",
  "display_order": 8
},
  [VARIABLE_CATEGORY_IDS.PRODUCTIVITY_AND_LEARNING]: {
  "id": "productivity-and-learning",
  "name": "Productivity and Learning",
  "short_description": "Work and education",
  "long_description": "Work, education, and goal-oriented efforts, including hours worked, tasks completed, courses finished, or test scores. Also known as productivity or study.",
  "emoji": "📚",
  "display_order": 9
},
};
