// Source table: public.unit_categories
// Do not edit this file manually, it will be overwritten.

import type { Database } from '@/lib/database.types';

type UnitCategory = Database['public']['Tables']['unit_categories']['Row'];

export const UNIT_CATEGORY_IDS = {
  AGE: 'age', // Age
  AIR_QUALITY: 'air-quality', // Air Quality
  CELL_COUNT: 'cell-count', // Cell Count
  CONCENTRATION: 'concentration', // Concentration
  CURRENCY: 'currency', // Currency
  DIMENSIONLESS: 'dimensionless', // Dimensionless
  ENERGY: 'energy', // Energy
  FREQUENCY: 'frequency', // Frequency
  LENGTH: 'length', // Length
  MASS: 'mass', // Mass
  NOISE: 'noise', // Noise
  PERCENTAGE: 'percentage', // Percentage
  PRESSURE: 'pressure', // Pressure
  RATE: 'rate', // Rate
  TEMPERATURE: 'temperature', // Temperature
  TIME: 'time', // Time
  VOLUME: 'volume', // Volume
  WEIGHT: 'weight', // Weight
} as const;

export const UNIT_CATEGORIES_DATA: Record<string, Partial<UnitCategory>> = {
  [UNIT_CATEGORY_IDS.AGE]: {
  "id": "age",
  "name": "Age",
  "description": "Units representing age (e.g., years)",
  "base_unit_id": "year-age",
  "emoji": "🎂"
},
  [UNIT_CATEGORY_IDS.AIR_QUALITY]: {
  "id": "air-quality",
  "name": "Air Quality",
  "description": "Units for air quality metrics (e.g., ppm)",
  "base_unit_id": "micrograms-per-cubic-meter",
  "emoji": "🌬️"
},
  [UNIT_CATEGORY_IDS.CELL_COUNT]: {
  "id": "cell-count",
  "name": "Cell Count",
  "description": "Units for cell counts (e.g., per microliter)",
  "base_unit_id": "per-microliter",
  "emoji": "🔬"
},
  [UNIT_CATEGORY_IDS.CONCENTRATION]: {
  "id": "concentration",
  "name": "Concentration",
  "description": "Units of concentration (e.g., mg/dL, mmol/L)",
  "base_unit_id": "millimoles-per-liter",
  "emoji": "🧪"
},
  [UNIT_CATEGORY_IDS.CURRENCY]: {
  "id": "currency",
  "name": "Currency",
  "description": "Units representing currency",
  "base_unit_id": "us-dollar",
  "emoji": "💰"
},
  [UNIT_CATEGORY_IDS.DIMENSIONLESS]: {
  "id": "dimensionless",
  "name": "Dimensionless",
  "description": "Units for counts, scores, and normalized ratings (typically 1)",
  "base_unit_id": "dimensionless-unit",
  "emoji": "🔢"
},
  [UNIT_CATEGORY_IDS.ENERGY]: {
  "id": "energy",
  "name": "Energy",
  "description": "Units of energy (e.g., kcal, kJ)",
  "base_unit_id": "kilojoule",
  "emoji": "⚡"
},
  [UNIT_CATEGORY_IDS.FREQUENCY]: {
  "id": "frequency",
  "name": "Frequency",
  "description": "Units of frequency (e.g., per day, per week)",
  "base_unit_id": "per-day",
  "emoji": "🔄"
},
  [UNIT_CATEGORY_IDS.LENGTH]: {
  "id": "length",
  "name": "Length",
  "description": "Units of length or distance",
  "base_unit_id": "meter",
  "emoji": "📏"
},
  [UNIT_CATEGORY_IDS.MASS]: {
  "id": "mass",
  "name": "Mass",
  "description": "Units of mass (distinct from weight)",
  "emoji": "⚖️"
},
  [UNIT_CATEGORY_IDS.NOISE]: {
  "id": "noise",
  "name": "Noise",
  "description": "Units of noise level (e.g., decibels)",
  "base_unit_id": "decibel",
  "emoji": "🔊"
},
  [UNIT_CATEGORY_IDS.PERCENTAGE]: {
  "id": "percentage",
  "name": "Percentage",
  "description": "Units representing a percentage",
  "base_unit_id": "percent",
  "emoji": "%"
},
  [UNIT_CATEGORY_IDS.PRESSURE]: {
  "id": "pressure",
  "name": "Pressure",
  "description": "Units of pressure (e.g., mmHg)",
  "base_unit_id": "pascal",
  "emoji": "💨"
},
  [UNIT_CATEGORY_IDS.RATE]: {
  "id": "rate",
  "name": "Rate",
  "description": "Units of rate (e.g., per minute)",
  "base_unit_id": "per-second",
  "emoji": "💓"
},
  [UNIT_CATEGORY_IDS.TEMPERATURE]: {
  "id": "temperature",
  "name": "Temperature",
  "description": "Units of temperature",
  "base_unit_id": "celsius",
  "emoji": "🌡️"
},
  [UNIT_CATEGORY_IDS.TIME]: {
  "id": "time",
  "name": "Time",
  "description": "Units of time duration",
  "base_unit_id": "second",
  "emoji": "⏱️"
},
  [UNIT_CATEGORY_IDS.VOLUME]: {
  "id": "volume",
  "name": "Volume",
  "description": "Units of volume",
  "base_unit_id": "liter",
  "emoji": "💧"
},
  [UNIT_CATEGORY_IDS.WEIGHT]: {
  "id": "weight",
  "name": "Weight",
  "description": "Units of weight (often used interchangeably with mass in context)",
  "base_unit_id": "kilogram",
  "emoji": "⚖️"
},
};
