// This file is auto-generated by scripts/generate-nav-tree.ts
// Do not edit this file directly.

// Maps snake_case path keys to navigation info
export interface SimpleNavInfo {
  name: string; // User-friendly name
  path: string; // Original URL path
}

export const navigationTreeObject: Record<string, SimpleNavInfo> = {
  "root": {
    "name": "Home",
    "path": "/"
  },
  "admin": {
    "name": "Admin",
    "path": "/admin"
  },
  "conditions": {
    "name": "Conditions",
    "path": "/conditions"
  },
  "conditions_conditionid": {
    "name": "Dynamic (conditionId)",
    "path": "/conditions/[conditionId]"
  },
  "conditions_conditionid_trials": {
    "name": "Trials",
    "path": "/conditions/[conditionId]/trials"
  },
  "contact": {
    "name": "Contact",
    "path": "/contact"
  },
  "developer": {
    "name": "Developer",
    "path": "/developer"
  },
  "developers": {
    "name": "Developers",
    "path": "/developers"
  },
  "developers_documentation": {
    "name": "Documentation",
    "path": "/developers/documentation"
  },
  "find_trials": {
    "name": "Find Trials",
    "path": "/find-trials"
  },
  "forgot_password": {
    "name": "Forgot Password",
    "path": "/forgot-password"
  },
  "impact": {
    "name": "Impact",
    "path": "/impact"
  },
  "login": {
    "name": "Login",
    "path": "/login"
  },
  "outcome_labels": {
    "name": "Outcome Labels",
    "path": "/outcome-labels"
  },
  "patient": {
    "name": "Patient",
    "path": "/patient"
  },
  "patient_data_submission": {
    "name": "Data Submission",
    "path": "/patient/data-submission"
  },
  "patient_join_trial": {
    "name": "Join Trial",
    "path": "/patient/join-trial"
  },
  "patient_join_trial_treatment": {
    "name": "Dynamic (treatment)",
    "path": "/patient/join-trial/[treatment]"
  },
  "patient_join_trial_treatment_condition": {
    "name": "Dynamic (condition)",
    "path": "/patient/join-trial/[treatment]/[condition]"
  },
  "patient_profile": {
    "name": "Profile",
    "path": "/patient/profile"
  },
  "patient_treatments": {
    "name": "Treatments",
    "path": "/patient/treatments"
  },
  "patient_trial_details": {
    "name": "Trial Details",
    "path": "/patient/trial-details"
  },
  "patient_trial_details_id": {
    "name": "Dynamic (id)",
    "path": "/patient/trial-details/[id]"
  },
  "patient_trial_payment": {
    "name": "Trial Payment",
    "path": "/patient/trial-payment"
  },
  "patient_trial_payment_id": {
    "name": "Dynamic (id)",
    "path": "/patient/trial-payment/[id]"
  },
  "privacy": {
    "name": "Privacy",
    "path": "/privacy"
  },
  "provider": {
    "name": "Provider",
    "path": "/provider"
  },
  "provider_ehr_authorization": {
    "name": "Ehr Authorization",
    "path": "/provider/ehr-authorization"
  },
  "provider_ehr_authorization_patientid": {
    "name": "Dynamic (patientId)",
    "path": "/provider/ehr-authorization/[patientId]"
  },
  "provider_form_management": {
    "name": "Form Management",
    "path": "/provider/form-management"
  },
  "provider_form_management_create": {
    "name": "Create",
    "path": "/provider/form-management/create"
  },
  "provider_intervention_assignment": {
    "name": "Intervention Assignment",
    "path": "/provider/intervention-assignment"
  },
  "provider_intervention_assignment_patientid": {
    "name": "Dynamic (patientId)",
    "path": "/provider/intervention-assignment/[patientId]"
  },
  "provider_patients": {
    "name": "Patients",
    "path": "/provider/patients"
  },
  "provider_patients_id": {
    "name": "Dynamic (id)",
    "path": "/provider/patients/[id]"
  },
  "provider_patients_id_enroll": {
    "name": "Enroll",
    "path": "/provider/patients/[id]/enroll"
  },
  "providers": {
    "name": "Providers",
    "path": "/providers"
  },
  "register": {
    "name": "Register",
    "path": "/register"
  },
  "research_partner": {
    "name": "Research Partner",
    "path": "/research-partner"
  },
  "research_partner_create_trial": {
    "name": "Create Trial",
    "path": "/research-partner/create-trial"
  },
  "research_partner_profile": {
    "name": "Profile",
    "path": "/research-partner/profile"
  },
  "research_partner_trials": {
    "name": "Trials",
    "path": "/research-partner/trials"
  },
  "research_partner_trials_id": {
    "name": "Dynamic (id)",
    "path": "/research-partner/trials/[id]"
  },
  "research_partner_trials_id_results": {
    "name": "Results",
    "path": "/research-partner/trials/[id]/results"
  },
  "select_role": {
    "name": "Select Role",
    "path": "/select-role"
  },
  "terms": {
    "name": "Terms",
    "path": "/terms"
  },
  "treatments": {
    "name": "Treatments",
    "path": "/treatments"
  },
  "treatments_id": {
    "name": "Dynamic (id)",
    "path": "/treatments/[id]"
  },
  "user": {
    "name": "User",
    "path": "/user"
  },
  "user_profile": {
    "name": "Profile",
    "path": "/user/profile"
  }
};
